// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJgKqlqgny9peLHRbXhpPiGhOfWXFQ_dQ',
    appId: '1:576761570066:web:e6f66177a94638cc88c9cb',
    messagingSenderId: '576761570066',
    projectId: 'ingresoya-fb6a6',
    authDomain: 'ingresoya-fb6a6.firebaseapp.com',
    storageBucket: 'ingresoya-fb6a6.firebasestorage.app',
    measurementId: 'G-YLK4DY6F49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP_36m3MFnfJ-MQLmyGcB--OK85yKgD7Y',
    appId: '1:576761570066:android:82d1b6ac6ec56b3d88c9cb',
    messagingSenderId: '576761570066',
    projectId: 'ingresoya-fb6a6',
    storageBucket: 'ingresoya-fb6a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3-tVf1rinQYZ8l3iB6dBfm3l9bHxGgRM',
    appId: '1:576761570066:ios:137b610fbe62b01d88c9cb',
    messagingSenderId: '576761570066',
    projectId: 'ingresoya-fb6a6',
    storageBucket: 'ingresoya-fb6a6.firebasestorage.app',
    iosBundleId: 'com.example.ingresoyaAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3-tVf1rinQYZ8l3iB6dBfm3l9bHxGgRM',
    appId: '1:576761570066:ios:137b610fbe62b01d88c9cb',
    messagingSenderId: '576761570066',
    projectId: 'ingresoya-fb6a6',
    storageBucket: 'ingresoya-fb6a6.firebasestorage.app',
    iosBundleId: 'com.example.ingresoyaAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJgKqlqgny9peLHRbXhpPiGhOfWXFQ_dQ',
    appId: '1:576761570066:web:5f3ebfaa067d28be88c9cb',
    messagingSenderId: '576761570066',
    projectId: 'ingresoya-fb6a6',
    authDomain: 'ingresoya-fb6a6.firebaseapp.com',
    storageBucket: 'ingresoya-fb6a6.firebasestorage.app',
    measurementId: 'G-39Z5PY4R4J',
  );
}
