// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvv5hAu77EL7VIXkmt54BdHx_53W9J9cQ',
    appId: '1:377388184823:web:b20f322549797fd4d98ff2',
    messagingSenderId: '377388184823',
    projectId: 'ingresoya-e5115',
    authDomain: 'ingresoya-e5115.firebaseapp.com',
    storageBucket: 'ingresoya-e5115.firebasestorage.app',
    measurementId: 'G-KDP155BQR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVpgV8_PlZGACefITx9fmhQZKU8yoPXjo',
    appId: '1:377388184823:android:ed9023b54142b537d98ff2',
    messagingSenderId: '377388184823',
    projectId: 'ingresoya-e5115',
    storageBucket: 'ingresoya-e5115.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCalkid6O8DdZqXRTSNdts6w7JnkI4unc8',
    appId: '1:377388184823:ios:ee3156ca1e5ee343d98ff2',
    messagingSenderId: '377388184823',
    projectId: 'ingresoya-e5115',
    storageBucket: 'ingresoya-e5115.firebasestorage.app',
    iosBundleId: 'com.example.ingresoyaAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCalkid6O8DdZqXRTSNdts6w7JnkI4unc8',
    appId: '1:377388184823:ios:ee3156ca1e5ee343d98ff2',
    messagingSenderId: '377388184823',
    projectId: 'ingresoya-e5115',
    storageBucket: 'ingresoya-e5115.firebasestorage.app',
    iosBundleId: 'com.example.ingresoyaAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvv5hAu77EL7VIXkmt54BdHx_53W9J9cQ',
    appId: '1:377388184823:web:2ee0da49c7cfda88d98ff2',
    messagingSenderId: '377388184823',
    projectId: 'ingresoya-e5115',
    authDomain: 'ingresoya-e5115.firebaseapp.com',
    storageBucket: 'ingresoya-e5115.firebasestorage.app',
    measurementId: 'G-2JL6YZ28HY',
  );
}
